#include "orca_android_core.hpp"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <filesystem>
#include <regex>
#include <sstream>
#include <utility>

#include <admesh/stl.h>

namespace orca_android_core {

struct ModelLoader::Impl {
    stl_file model;
    std::string config_json;
    std::string gcode;
};

namespace {

constexpr const char* DEFAULT_CONFIG_JSON = R"({
    "layer_height": 0.2,
    "first_layer_height": 0.2,
    "travel_speed": 120
})";

bool has_stl_extension(const std::filesystem::path& path)
{
    if (!path.has_extension()) {
        return false;
    }

    std::string extension = path.extension().string();
    std::transform(extension.begin(), extension.end(), extension.begin(), [](unsigned char ch) {
        return static_cast<char>(std::tolower(ch));
    });
    return extension == ".stl";
}

// Mirrors Orca's TriangleMesh::repair() import path while keeping the Android
// core scoped to STL parsing and repair only.
void repair_on_import(stl_file& stl)
{
    if (stl.stats.number_of_facets == 0) {
        return;
    }

    stl_check_facets_exact(&stl);
    stl.stats.facets_w_1_bad_edge = stl.stats.connected_facets_2_edge - stl.stats.connected_facets_3_edge;
    stl.stats.facets_w_2_bad_edge = stl.stats.connected_facets_1_edge - stl.stats.connected_facets_2_edge;
    stl.stats.facets_w_3_bad_edge = stl.stats.number_of_facets - stl.stats.connected_facets_1_edge;

    float tolerance = static_cast<float>(stl.stats.shortest_edge);
    float increment = static_cast<float>(stl.stats.bounding_diameter) / 10000.0f;
    constexpr int iterations = 2;
    if (stl.stats.connected_facets_3_edge < static_cast<int>(stl.stats.number_of_facets)) {
        for (int iteration = 0; iteration < iterations; ++iteration) {
            if (stl.stats.connected_facets_3_edge >= static_cast<int>(stl.stats.number_of_facets)) {
                break;
            }
            stl_check_facets_nearby(&stl, tolerance);
            tolerance += increment;
        }
    }

    if (stl.stats.connected_facets_3_edge < static_cast<int>(stl.stats.number_of_facets)) {
        stl_remove_unconnected_facets(&stl);
    }

    stl_fix_normal_directions(&stl);
    stl_fix_normal_values(&stl);
    stl_calculate_volume(&stl);
    stl_verify_neighbors(&stl);

    if (stl.stats.number_of_facets > 0 && stl.stats.degenerate_facets > 0) {
        stl_check_facets_exact(&stl);
    }
}

float extract_number_or_default(const std::string& json, const char* key, float fallback)
{
    const std::regex pattern(std::string("\"") + key + "\"\\s*:\\s*(-?[0-9]+(?:\\.[0-9]+)?)");
    std::smatch match;
    if (!std::regex_search(json, match, pattern) || match.size() < 2) {
        return fallback;
    }

    try {
        return std::stof(match[1].str());
    } catch (...) {
        return fallback;
    }
}

std::string build_minimal_gcode(const stl_file& stl, const std::string& config_json)
{
    const float layer_height = extract_number_or_default(config_json, "layer_height", 0.2f);
    const float first_layer_height = extract_number_or_default(config_json, "first_layer_height", layer_height);
    const float travel_speed = extract_number_or_default(config_json, "travel_speed", 120.0f);
    if (!(layer_height > 0.0f) || !(first_layer_height > 0.0f) || !(travel_speed > 0.0f)) {
        return {};
    }
    if (!(stl.stats.size.z() > 0.0f) || !std::isfinite(stl.stats.size.z())) {
        return {};
    }

    const float model_height = stl.stats.size.z();
    int layer_count = 1;
    if (model_height > first_layer_height) {
        layer_count += static_cast<int>(std::ceil((model_height - first_layer_height) / layer_height));
    }
    layer_count = std::max(layer_count, 1);

    std::ostringstream gcode;
    gcode << "; generated by orca_core_android\n";
    gcode << "; source=orcaslicer_android_wrapper\n";
    gcode << "; facets=" << stl.stats.number_of_facets << "\n";
    gcode << "; model_height_mm=" << model_height << "\n";
    gcode << "; layer_height_mm=" << layer_height << "\n";
    gcode << "G90\n";
    gcode << "G21\n";
    gcode << "G28\n";
    gcode << "G1 F" << travel_speed * 60.0f << "\n";

    float current_z = std::max(first_layer_height, 0.0f);
    for (int layer_index = 0; layer_index < layer_count; ++layer_index) {
        gcode << ";LAYER:" << layer_index << "\n";
        gcode << "G1 Z" << current_z << "\n";
        gcode << "G1 X" << stl.stats.min.x() << " Y" << stl.stats.min.y() << "\n";
        gcode << "G1 X" << stl.stats.max.x() << " Y" << stl.stats.min.y() << "\n";
        gcode << "G1 X" << stl.stats.max.x() << " Y" << stl.stats.max.y() << "\n";
        gcode << "G1 X" << stl.stats.min.x() << " Y" << stl.stats.max.y() << "\n";
        gcode << "G1 X" << stl.stats.min.x() << " Y" << stl.stats.min.y() << "\n";
        current_z += layer_height;
    }

    gcode << "M400\n";
    gcode << "M84\n";
    return gcode.str();
}

} // namespace

ModelLoader::~ModelLoader()
{
    clear();
}

bool ModelLoader::load_model(const char* path)
{
    clear();

    if (path == nullptr || path[0] == '\0') {
        return false;
    }

    const std::filesystem::path model_path(path);
    if (!std::filesystem::exists(model_path) ||
        !std::filesystem::is_regular_file(model_path) ||
        !has_stl_extension(model_path)) {
        return false;
    }

    stl_file parsed_model;
    if (!stl_open(&parsed_model, model_path.string().c_str(), nullptr, 80)) {
        return false;
    }

    repair_on_import(parsed_model);
    if (parsed_model.stats.number_of_facets == 0) {
        return false;
    }

    impl_ = new Impl();
    impl_->model = std::move(parsed_model);
    impl_->config_json = DEFAULT_CONFIG_JSON;
    loaded_path_ = std::filesystem::absolute(model_path).string();
    has_model_ = true;
    return true;
}

bool ModelLoader::set_config_json(const char* json)
{
    if (json == nullptr) {
        return false;
    }
    if (impl_ == nullptr) {
        impl_ = new Impl();
    }

    impl_->config_json = json;
    return true;
}

bool ModelLoader::slice()
{
    if (impl_ == nullptr || !has_model_) {
        return false;
    }
    if (!stl_validate(&impl_->model)) {
        return false;
    }

    const std::string& config_json = impl_->config_json.empty() ? std::string(DEFAULT_CONFIG_JSON) : impl_->config_json;
    impl_->gcode = build_minimal_gcode(impl_->model, config_json);
    return !impl_->gcode.empty();
}

void ModelLoader::clear_generated_gcode()
{
    if (impl_ != nullptr) {
        impl_->gcode.clear();
    }
}

void ModelLoader::clear()
{
    if (impl_ != nullptr) {
        impl_->model.clear();
    }
    delete impl_;
    impl_ = nullptr;
    loaded_path_.clear();
    has_model_ = false;
}

bool ModelLoader::has_model() const
{
    return has_model_;
}

const std::string& ModelLoader::loaded_path() const
{
    return loaded_path_;
}

const std::string& ModelLoader::gcode() const
{
    static const std::string empty;
    return impl_ != nullptr ? impl_->gcode : empty;
}

} // namespace orca_android_core
