package com.mobileslicer.profiles

internal data class FilamentProfile(
    val id: String,
    val name: String,
    val subtitle: String,
    val builtIn: Boolean,
    val materialType: String,
    val vendor: String = "(Undefined)",
    val soluble: Boolean = false,
    val supportMaterial: Boolean = false,
    val filamentExtruderVariant: String = "Direct Drive Standard",
    val filamentSelfIndex: String = "1",
    val filamentChangeLengthMm: Float = 10f,
    val requiredNozzleHrc: Int = 0,
    val defaultFilamentColor: String = "",
    val diameterMm: Float = 1.75f,
    val adhesivenessCategory: Int = 0,
    val densityGPerCm3: Float,
    val shrinkageXyPercent: Float = 100f,
    val shrinkageZPercent: Float = 100f,
    val costPerKg: Float = 0f,
    val softeningTemperatureC: Int = 100,
    val idleTemperatureC: Int = 0,
    val nozzleTemperatureRangeLowC: Int = 190,
    val nozzleTemperatureRangeHighC: Int = 240,
    val flowRatio: Float,
    val retractionLengthMm: Float?,
    val zHopMm: Float? = null,
    val zHopType: ZHopType? = null,
    val retractLiftAboveMm: Float? = null,
    val retractLiftBelowMm: Float? = null,
    val retractLiftEnforce: RetractLiftEnforce? = null,
    val retractionSpeedMmPerSec: Float?,
    val deretractionSpeedMmPerSec: Float?,
    val retractRestartExtraMm: Float? = null,
    val retractionMinimumTravelMm: Float? = null,
    val retractWhenChangingLayer: Boolean? = null,
    val wipe: Boolean? = null,
    val wipeDistanceMm: Float? = null,
    val retractBeforeWipePercent: Int? = null,
    val longRetractionsWhenCut: Boolean? = null,
    val retractionDistancesWhenCut: String = "",
    val ironingFlowPercent: Float? = null,
    val ironingSpacingMm: Float? = null,
    val ironingInsetMm: Float? = null,
    val ironingSpeedMmPerSec: Float? = null,
    val pressureAdvanceEnabled: Boolean,
    val pressureAdvance: Float,
    val pelletFlowCoefficient: Float = 0.4157f,
    val adaptivePressureAdvanceEnabled: Boolean = false,
    val adaptivePressureAdvanceOverhangsEnabled: Boolean = false,
    val adaptivePressureAdvanceBridges: Float = 0f,
    val adaptivePressureAdvanceModel: String = "0,0,0\n0,0,0",
    val maxVolumetricSpeedMm3PerSec: Float,
    val adaptiveVolumetricSpeedEnabled: Boolean,
    val volumetricSpeedCoefficients: String,
    val nozzleTemperatureInitialLayerC: Int,
    val nozzleTemperatureC: Int,
    val chamberTemperatureC: Int = 0,
    val activateChamberTemperatureControl: Boolean = false,
    val supertackPlateTemperatureInitialLayerC: Int = 35,
    val supertackPlateTemperatureC: Int = 35,
    val coolPlateTemperatureInitialLayerC: Int = 35,
    val coolPlateTemperatureC: Int = 35,
    val texturedCoolPlateTemperatureInitialLayerC: Int = 40,
    val texturedCoolPlateTemperatureC: Int = 40,
    val engineeringPlateTemperatureInitialLayerC: Int = 45,
    val engineeringPlateTemperatureC: Int = 45,
    val bedTemperatureInitialLayerC: Int,
    val bedTemperatureC: Int,
    val texturedPlateTemperatureInitialLayerC: Int = 45,
    val texturedPlateTemperatureC: Int = 45,
    val minFanSpeedPercent: Int = 30,
    val coolingPercent: Int,
    val noCoolingFirstLayers: Int,
    val fullFanSpeedLayer: Int = 0,
    val fanCoolingLayerTimeSeconds: Float = 60f,
    val slowDownLayerTimeSeconds: Float = 5f,
    val reduceFanStopStartFrequency: Boolean = false,
    val slowDownForLayerCooling: Boolean = true,
    val dontSlowDownOuterWall: Boolean = false,
    val slowDownMinSpeedMmPerSec: Float = 10f,
    val enableOverhangBridgeFan: Boolean = true,
    val overhangFanThreshold: String = "95%",
    val overhangFanSpeedPercent: Int = 100,
    val internalBridgeFanSpeedPercent: Int = -1,
    val supportMaterialInterfaceFanSpeedPercent: Int = -1,
    val ironingFanSpeedPercent: Int = -1,
    val additionalCoolingFanSpeedPercent: Int = 0,
    val activateAirFiltration: Boolean = false,
    val duringPrintExhaustFanSpeedPercent: Int = 60,
    val completePrintExhaustFanSpeedPercent: Int = 80,
    val minimalPurgeOnWipeTowerMm3: Float = 15f,
    val towerInterfacePreExtrusionDistanceMm: Float = 10f,
    val towerInterfacePreExtrusionLengthMm: Float = 0f,
    val towerIroningAreaMm2: Float = 4f,
    val towerInterfacePurgeVolumeMm: Float = 20f,
    val towerInterfacePrintTemperatureC: Int = -1,
    val longRetractionsWhenExtruderChange: Boolean? = null,
    val retractionDistanceWhenExtruderChangeMm: Float? = null,
    val loadingSpeedStartMmPerSec: Float = 3f,
    val loadingSpeedMmPerSec: Float = 28f,
    val unloadingSpeedStartMmPerSec: Float = 100f,
    val unloadingSpeedMmPerSec: Float = 90f,
    val toolchangeDelaySeconds: Float = 0f,
    val coolingMoves: Int = 4,
    val coolingInitialSpeedMmPerSec: Float = 2.2f,
    val coolingFinalSpeedMmPerSec: Float = 3.4f,
    val stampingLoadingSpeedMmPerSec: Float = 0f,
    val stampingDistanceMm: Float = 0f,
    val rammingParameters: String = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6",
    val multitoolRamming: Boolean = false,
    val multitoolRammingVolumeMm3: Float = 10f,
    val multitoolRammingFlowMm3PerSec: Float = 10f,
    val compatiblePrinters: String = "",
    val compatiblePrintersCondition: String = "",
    val compatiblePrints: String = "",
    val compatiblePrintsCondition: String = "",
    val filamentNotes: String = "",
    val filamentStartGcode: String = "",
    val filamentEndGcode: String = "",
    val printerProfileId: String = "",
    val profileSource: String = "custom",
    val orcaFamily: String = "",
	    val orcaFilamentPath: String = "",
	    val orcaRawFilamentJson: String = "",
	    val orcaResolvedFilamentJson: String = "",
	    val orcaFilamentOverridesJson: String = "",
	    val orcaResolvedSourceChain: List<String> = emptyList()
)
