#!/usr/bin/env python3
import argparse
import re
from pathlib import Path


MODE_DEFAULT = "Default"


def kotlin_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def find_line(text: str, index: int) -> int:
    return text.count("\n", 0, index) + 1


def parse_config_defs(path: Path) -> dict[str, dict[str, object]]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    matches = list(
        re.finditer(
            r'(def\s*=\s*this->add\("(?P<key1>[^"]+)",\s*(?P<type1>co\w+)\)|'
            r'new_def\("(?P<key2>[^"]+)",\s*(?P<type2>co\w+),\s*"(?P<label2>[^"]*)")',
            text,
        )
    )
    defs: dict[str, dict[str, object]] = {}
    for index, match in enumerate(matches):
        key = match.group("key1") or match.group("key2")
        config_type = match.group("type1") or match.group("type2")
        block_end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        block = text[match.start() : block_end]
        mode_match = re.search(r"def->mode\s*=\s*(com\w+)", block)
        label_match = re.search(r'def->label\s*=\s*L\("([^"]*)"\)', block)
        category_match = re.search(r'def->category\s*=\s*L\("([^"]*)"\)', block)
        default_match = re.search(r"set_default_value\(([^;]+)\);", block, re.S)
        enum_values = re.findall(r'enum_values\.push_back\("([^"]+)"\)', block)
        defs[key] = {
            "key": key,
            "configType": config_type,
            "mode": mode_match.group(1) if mode_match else MODE_DEFAULT,
            "label": label_match.group(1) if label_match else (match.group("label2") or ""),
            "category": category_match.group(1) if category_match else "",
            "defaultValue": " ".join(default_match.group(1).split()) if default_match else "",
            "enumValues": enum_values,
            "sourceLine": find_line(text, match.start()),
        }
    return defs


def parse_gui_placements(path: Path) -> dict[str, list[dict[str, object]]]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    placements: dict[str, list[dict[str, object]]] = {}
    page = ""
    group = ""
    for line_number, line in enumerate(text.splitlines(), start=1):
        page_match = re.search(r'add_options_page\(L\("([^"]+)"', line)
        if page_match:
            page = page_match.group(1)
            group = ""
        group_match = re.search(r'new_optgroup\(L\("([^"]+)"', line)
        if group_match:
            group = group_match.group(1)
        keys = re.findall(r'(?:append_single_option_line|get_option)\("([^"]+)"', line)
        for key in keys:
            placements.setdefault(key, []).append(
                {
                    "page": page,
                    "group": group,
                    "sourceLine": line_number,
                }
            )
    return placements


def render_generated(defs: dict[str, dict[str, object]], placements: dict[str, list[dict[str, object]]]) -> str:
    all_keys = sorted(set(defs) | set(placements))
    lines: list[str] = [
        "package com.mobileslicer.profiles",
        "",
        "// Generated by scripts/generate_orca_setting_metadata.py from vendor/orcaslicer.",
        "// Do not edit by hand; edit Orca sources or ProfileSettingVisibility overrides.",
        "internal object GeneratedOrcaSettingMetadata {",
        "    val all: Map<String, OrcaSettingMetadata> = mapOf(",
    ]
    for key in all_keys:
        definition = defs.get(key)
        gui = placements.get(key, [])
        lines.append(f"        {kotlin_string(key)} to OrcaSettingMetadata(")
        lines.append(f"            key = {kotlin_string(key)},")
        lines.append(f"            configType = {kotlin_string(str(definition.get('configType', '') if definition else ''))},")
        lines.append(f"            mode = {kotlin_string(str(definition.get('mode', '') if definition else ''))},")
        lines.append(f"            label = {kotlin_string(str(definition.get('label', '') if definition else ''))},")
        lines.append(f"            category = {kotlin_string(str(definition.get('category', '') if definition else ''))},")
        lines.append(f"            defaultValue = {kotlin_string(str(definition.get('defaultValue', '') if definition else ''))},")
        enum_values = definition.get("enumValues", []) if definition else []
        lines.append("            enumValues = listOf(" + ", ".join(kotlin_string(v) for v in enum_values) + "),")
        source_line = int(definition.get("sourceLine", 0)) if definition else 0
        lines.append(f"            printConfigLine = {source_line},")
        lines.append("            guiPlacements = listOf(")
        for placement in gui:
            lines.append(
                "                OrcaGuiPlacement("
                f"page = {kotlin_string(str(placement['page']))}, "
                f"group = {kotlin_string(str(placement['group']))}, "
                f"tabCppLine = {int(placement['sourceLine'])}"
                "),"
            )
        lines.append("            )")
        suffix = "," if key != all_keys[-1] else ""
        lines.append(f"        ){suffix}")
    lines.extend(
        [
            "    )",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    repo = args.repo_root.resolve()
    defs = parse_config_defs(repo / "vendor/orcaslicer/src/libslic3r/PrintConfig.cpp")
    placements = parse_gui_placements(repo / "vendor/orcaslicer/src/slic3r/GUI/Tab.cpp")
    output = render_generated(defs, placements)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
