#ifndef ORCA_ANDROID_CORE_BOOST_PREDEF_OTHER_ENDIAN_H
#define ORCA_ANDROID_CORE_BOOST_PREDEF_OTHER_ENDIAN_H

#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#define BOOST_ENDIAN_BIG_BYTE 1
#define BOOST_ENDIAN_LITTLE_BYTE 0
#else
#define BOOST_ENDIAN_BIG_BYTE 0
#define BOOST_ENDIAN_LITTLE_BYTE 1
#endif

#endif
